apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
  labels:
    app: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: url-shortener:latest
        imagePullPolicy: Never
        env:
          - name: URL_SHORTENER_POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: url-shortener-secret
                key: URL_SHORTENER_POSTGRES_PASSWORD

          - name: URL_SHORTENER_POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: url-shortener-secret
                key: URL_SHORTENER_POSTGRES_USER
          - name: URL_SHORTENER_DATASOURCE
            valueFrom:
              configMapKeyRef:
                name: url-shortener-config
                key: URL_SHORTENER_DATASOURCE

---
#Service

apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  type: NodePort
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
    # The range of valid ports is 30000-32767
      nodePort: 30001


